# Workflow의 이름
name: Deploy To EC2

# Event: 실행되는 시점
on:
  push:
    branches:
      - master

jobs:

  # job 식별
  Deploy:

    # ubuntu 환경 / 가장 최신 버전(latest)
    runs-on: ubuntu-latest

    # step: 특정 작업을 수행하는 가장 작은 단위 (linux 명령어)
    steps:

      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Node 설치
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 의존성(라이브러리) 설치
        run: pnpm i

      - name: .env 파일 만들기
        run: echo '${{ secrets.ENV }}' >> .env

#      - name: prisma setting
#        run: pnpm prisma generate

      - name: 테스트 코드 실행
        run: npm run test

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t playground-server .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag playground-server ${{ steps.login-ecr.outputs.registry }}/playground-server:latest

      - name: ECR에 Docker 이미지 Push하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/playground-server:latest

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop playground-server || true
            docker rm playground-server || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/playground-server:latest
            docker run -d --name playground-server -p 4080:3090 ${{ steps.login-ecr.outputs.registry }}/playground-server:latest