# Workflow의 이름
name: Deploy To EC2

# Event: 실행되는 시점
on:
  push:
    branches:
      - master

jobs:

  # job 식별
  Deploy:

    # ubuntu 환경 / 가장 최신 버전(latest)
    runs-on: ubuntu-latest

    # step: 특정 작업을 수행하는 가장 작은 단위 (linux 명령어)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3 # 라이브러리
        env:
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: false # 아래 script 중 실패하는 명령이 하나라도 있으면 실패로 처리
          envs: ENV
          script: |
            cd /home/ubuntu/server/nestjs-prisma-playground
            git pull origin master
            
            echo "$ENV" > .env
            
            # npm 및 pm2 설치
            sudo npm install -g npm
            sudo npm install -g pm2
            
            npm i 
            npm run build
            pm2 kill
            pm2 start dist/main.js --name "playground-server"
